version: '3.3'
services:
  client:
    image: jeffli1981/mern-stack-client
    stdin_open: true
    build: .
    ports:
      - "3001:3001"
    # networks:
    #   - mern-stack
  server:
    image: jeffli1981/mern-stack-server
    build: .
    ports: 
      - "80:8080"
    # networks:
    #   - mern-stack
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:

# networks:
#   mern-stack:
#     driver: bridge